=== giserh/sdk-gen/data/schemas/game_schema.json
{
   "$schema":"http://json-schema.org/draft-03/schema",
   "description":"A representation of a game",
   "type":"object",
   "properties":{
      "active":{
         "required":false,
         "type":"boolean",
         "default":"false"
      },
      "name":{
         "required":true,
         "type":"string"
      },
      "description":{
         "required":false,
         "type":"string"
      },
      "expression":{
         "required":true,
         "type":"string"
      },
      "priority":{
         "required":false,
         "type":"int",
         "default":"1"
      },
      "gameType":{
         "required":false,
         "type":"string",
         "allowed":{
            "0":"ONE_TIME",
            "1":"GRADUAL"
         },
         "default":"ONE_TIME"
      },
      "notifications":{
         "required":false,
         "type":"id_array"
      },
      "conditions":{
         "required":false,
         "type":"id_array"
      },
      "counter":{
         "required":false,
         "type":"id"
      },
      "transactionSource":{
         "required":false,
         "type":"id"
      }
   }
}

=== giserh/sdk-gen/data/examples/admin/game_post_example.json
{
    "active": false,
    "conditions": [
        1,
        2,
        3
    ],
    "counter": 1,
    "description": "Example description",
    "expression": "{1} AND ({2} OR {3})",
    "gameType": "ONE_TIME",
    "name": "Example",
    "notifications": [
        2,
        4
    ],
    "priority": 1,
    "transactionSource": 1
}
